# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Core Properties #
nifi.flow.configuration.file=target/nifi-storage/conf/flow.json.gz
nifi.flow.configuration.archive.dir=target/nifi-storage/conf/archive/
nifi.flowcontroller.graceful.shutdown.period=10 sec

# State Management #
nifi.state.management.configuration.file=target/nifi-storage/state-management.xml
nifi.state.management.provider.local=local-provider

# Database Settings
nifi.database.directory=target/nifi-storage/database_repository

# FlowFile Repository
nifi.flowfile.repository.implementation=org.apache.nifi.controller.repository.WriteAheadFlowFileRepository
nifi.flowfile.repository.wal.implementation=org.apache.nifi.wali.SequentialAccessWriteAheadLog
nifi.flowfile.repository.directory=target/nifi-storage/flowfile_repository

# Content Repository
nifi.content.repository.implementation=org.apache.nifi.controller.repository.FileSystemRepository
nifi.content.repository.directory.default=target/nifi-storage/content_repository
nifi.content.repository.archive.enabled=false

# Provenance Repository Properties
nifi.provenance.repository.implementation=org.apache.nifi.provenance.VolatileProvenanceRepository
nifi.provenance.repository.buffer.size=1000

# Component Status Repository
nifi.components.status.repository.implementation=org.apache.nifi.controller.status.history.VolatileComponentStatusRepository

# NAR Persistence Provider Properties
nifi.nar.persistence.provider.properties.directory=target/nifi-storage/nar_repository

# Asset Management
nifi.asset.manager.properties.directory=target/nifi-storage/assets

# Connector Asset Manager
nifi.connector.asset.manager.implementation=org.apache.nifi.mock.connector.server.MockConnectorAssetManager

# Secrets Manager
nifi.secrets.manager.implementation=org.apache.nifi.mock.connector.server.secrets.ConnectorTestRunnerSecretsManager

# Web Properties #
nifi.web.http.host=
nifi.web.http.port=
nifi.web.https.host=localhost
nifi.web.https.port=0
nifi.web.jetty.working.directory=target/work/jetty

# Security Properties #
nifi.sensitive.props.key=nifi-connector-mock-tests
nifi.sensitive.props.algorithm=NIFI_PBKDF2_AES_GCM_256
nifi.security.keystore=
nifi.security.keystoreType=PKCS12
nifi.security.keystorePasswd=
nifi.security.keyPasswd=
nifi.security.truststore=
nifi.security.truststoreType=PKCS12
nifi.security.truststorePasswd=
nifi.security.user.authorizer=system-test-authorizer
nifi.security.user.login.identity.provider=

# Cluster Properties #
nifi.cluster.is.node=false

# Connector Repository
nifi.components.connectors.repository.implementation=org.apache.nifi.mock.connector.server.MockConnectorRepository
