<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <!-- Licensed to the Apache Software Foundation (ASF) under one or more
        contributor license agreements. See the NOTICE file distributed with this
        work for additional information regarding copyright ownership. The ASF licenses
        this file to You under the Apache License, Version 2.0 (the "License"); you
        may not use this file except in compliance with the License. You may obtain
        a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless
        required by applicable law or agreed to in writing, software distributed
        under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
        OR CONDITIONS OF ANY KIND, either express or implied. See the License for
        the specific language governing permissions and limitations under the License. -->
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.apache.nifi</groupId>
        <artifactId>nifi-record-serialization-services-bundle</artifactId>
        <version>2.13.0-SNAPSHOT</version>
    </parent>
    <artifactId>nifi-record-serialization-services</artifactId>
    <packaging>jar</packaging>
    <dependencies>
        <dependency>
            <groupId>org.apache.nifi</groupId>
            <artifactId>nifi-utils</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.nifi</groupId>
            <artifactId>nifi-record-serialization-service-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.nifi</groupId>
            <artifactId>nifi-record</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.nifi</groupId>
            <artifactId>nifi-schema-registry-service-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.nifi</groupId>
            <artifactId>nifi-record-serialization-services-shared</artifactId>
            <version>2.13.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.apache.nifi</groupId>
            <artifactId>nifi-avro-record-utils</artifactId>
            <version>2.13.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.apache.nifi</groupId>
            <artifactId>nifi-syslog-utils</artifactId>
            <version>2.13.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.apache.nifi</groupId>
            <artifactId>nifi-xml-processing</artifactId>
            <version>2.13.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.apache.nifi</groupId>
            <artifactId>nifi-json-record-utils</artifactId>
            <version>2.13.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.apache.nifi</groupId>
            <artifactId>nifi-standard-record-utils</artifactId>
            <version>2.13.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.apache.nifi</groupId>
            <artifactId>nifi-yaml-record-utils</artifactId>
            <version>2.13.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-csv</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-csv</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>de.siegmar</groupId>
            <artifactId>fastcsv</artifactId>
            <version>4.4.0</version>
        </dependency>
        <dependency>
            <groupId>com.github.palindromicity</groupId>
            <artifactId>simple-syslog-5424</artifactId>
            <version>${simple-syslog-5424.version}</version>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
        </dependency>
        <dependency>
            <groupId>io.krakens</groupId>
            <artifactId>java-grok</artifactId>
            <version>0.1.9</version>
        </dependency>
        <dependency>
            <groupId>org.apache.avro</groupId>
            <artifactId>avro</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.ben-manes.caffeine</groupId>
            <artifactId>caffeine</artifactId>
        </dependency>
        <dependency>
            <groupId>net.java.dev.stax-utils</groupId>
            <artifactId>stax-utils</artifactId>
            <version>20070216</version>
            <exclusions>
                <exclusion>
                    <groupId>com.bea.xml</groupId>
                    <artifactId>jsr173-ri</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.xmlunit</groupId>
            <artifactId>xmlunit-matchers</artifactId>
            <version>2.14.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.xmlunit</groupId>
            <artifactId>xmlunit-core</artifactId>
            <version>2.14.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-text</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-compress</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fluenda</groupId>
            <artifactId>parcefone</artifactId>
            <version>3.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.jayway.jsonpath</groupId>
            <artifactId>json-path</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.nifi</groupId>
            <artifactId>nifi-mock-record-utils</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.nifi</groupId>
            <artifactId>nifi-schema-inference-utils</artifactId>
            <version>2.13.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.tukaani</groupId>
            <artifactId>xz</artifactId>
            <version>1.12</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.xerial.snappy</groupId>
            <artifactId>snappy-java</artifactId>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.rat</groupId>
                <artifactId>apache-rat-plugin</artifactId>
                <configuration>
                    <inputExcludes combine.children="append">
                        <inputExclude>src/test/resources/avro/avro_embed_schema.avro</inputExclude>
                        <inputExclude>src/test/resources/avro/avro_schemaless.avro</inputExclude>
                        <inputExclude>src/test/resources/avro/avro_schemaless_decimal.avro</inputExclude>
                        <inputExclude>src/test/resources/avro/avro_schemaless_decimal.avsc</inputExclude>
                        <inputExclude>src/test/resources/avro/datatypes.avsc</inputExclude>
                        <inputExclude>src/test/resources/avro/decimals.avsc</inputExclude>
                        <inputExclude>src/test/resources/avro/decimals-bytes-fixed.avsc</inputExclude>
                        <inputExclude>src/test/resources/avro/fixed16.avsc</inputExclude>
                        <inputExclude>src/test/resources/avro/logical-types.avsc</inputExclude>
                        <inputExclude>src/test/resources/avro/logical-types-nullable.avsc</inputExclude>
                        <inputExclude>src/test/resources/avro/multiple-types.avsc</inputExclude>
                        <inputExclude>src/test/resources/avro/simple.avsc</inputExclude>
                        <inputExclude>src/test/resources/avro/recursive.avsc</inputExclude>
                        <inputExclude>src/test/resources/avro/schemaless_simple_record.avsc</inputExclude>
                        <inputExclude>src/test/resources/avro/schemaless_simple_record_extra_field.avsc</inputExclude>

                        <inputExclude>src/test/resources/cef/empty-row.txt</inputExclude>
                        <inputExclude>src/test/resources/cef/misformatted-row.txt</inputExclude>
                        <inputExclude>src/test/resources/cef/multiple-rows.txt</inputExclude>
                        <inputExclude>src/test/resources/cef/multiple-rows-decreasing-number-of-extensions.txt</inputExclude>
                        <inputExclude>src/test/resources/cef/multiple-rows-increasing-number-of-extensions.txt</inputExclude>
                        <inputExclude>src/test/resources/cef/multiple-rows-starting-with-empty-row.txt</inputExclude>
                        <inputExclude>src/test/resources/cef/multiple-rows-with-different-custom-types.txt</inputExclude>
                        <inputExclude>src/test/resources/cef/multiple-rows-with-empty-rows.txt</inputExclude>
                        <inputExclude>src/test/resources/cef/single-row-header-fields-only.txt</inputExclude>
                        <inputExclude>src/test/resources/cef/single-row-with-custom-extensions.txt</inputExclude>
                        <inputExclude>src/test/resources/cef/single-row-with-empty-extension.txt</inputExclude>
                        <inputExclude>src/test/resources/cef/single-row-with-empty-custom-extensions.txt</inputExclude>
                        <inputExclude>src/test/resources/cef/single-row-with-extensions.txt</inputExclude>
                        <inputExclude>src/test/resources/cef/single-row-with-incorrect-custom-extensions.txt</inputExclude>
                        <inputExclude>src/test/resources/cef/single-row-with-incorrect-header-field.txt</inputExclude>

                        <inputExclude>src/test/resources/csv/extra-white-space.csv</inputExclude>
                        <inputExclude>src/test/resources/csv/multi-bank-account.csv</inputExclude>
                        <inputExclude>src/test/resources/csv/multi-bank-account_RFC4180.csv</inputExclude>
                        <inputExclude>src/test/resources/csv/single-bank-account.csv</inputExclude>
                        <inputExclude>src/test/resources/csv/single-bank-account_RFC4180.csv</inputExclude>
                        <inputExclude>src/test/resources/csv/multi-bank-account_escapechar.csv</inputExclude>
                        <inputExclude>src/test/resources/csv/multi-bank-account_escapechar_RFC4180.csv</inputExclude>
                        <inputExclude>src/test/resources/csv/multi-bank-account_spec_delimiter.csv</inputExclude>
                        <inputExclude>src/test/resources/csv/prov-events.csv</inputExclude>

                        <inputExclude>src/test/resources/grok/error-with-stack-trace.log</inputExclude>
                        <inputExclude>src/test/resources/grok/nifi-log-sample-multiline-with-stacktrace.log</inputExclude>
                        <inputExclude>src/test/resources/grok/nifi-log-sample.log</inputExclude>
                        <inputExclude>src/test/resources/grok/single-line-log-messages.txt</inputExclude>
                        <inputExclude>src/test/resources/grok/grok_patterns.txt</inputExclude>

                        <inputExclude>src/test/resources/json/bank-account-array-different-schemas.json</inputExclude>
                        <inputExclude>src/test/resources/json/bank-account-array-optional-balance.json</inputExclude>
                        <inputExclude>src/test/resources/json/bank-account-array.json</inputExclude>
                        <inputExclude>src/test/resources/json/bank-account-comments.jsonc</inputExclude>
                        <inputExclude>src/test/resources/json/bank-account-mixed.json</inputExclude>
                        <inputExclude>src/test/resources/json/bank-account-multiarray.json</inputExclude>
                        <inputExclude>src/test/resources/json/bank-account-multiline.json</inputExclude>
                        <inputExclude>src/test/resources/json/bank-account-oneline.json</inputExclude>
                        <inputExclude>src/test/resources/json/similar-records.json</inputExclude>
                        <inputExclude>src/test/resources/json/choice-of-array-empty-or-array-record.json</inputExclude>
                        <inputExclude>src/test/resources/json/empty-arrays.json</inputExclude>
                        <inputExclude>src/test/resources/json/choice-of-embedded-similar-records.json</inputExclude>
                        <inputExclude>src/test/resources/json/choice-of-embedded-arrays-and-single-records.json</inputExclude>
                        <inputExclude>src/test/resources/json/choice-of-merged-embedded-arrays-and-single-records.json</inputExclude>
                        <inputExclude>src/test/resources/json/choice-of-different-arrays-with-extra-fields.json</inputExclude>
                        <inputExclude>src/test/resources/json/data-types.json</inputExclude>
                        <inputExclude>src/test/resources/json/timestamp.json</inputExclude>
                        <inputExclude>src/test/resources/json/json-with-unicode.json</inputExclude>
                        <inputExclude>src/test/resources/json/multiple-nested-field.json</inputExclude>
                        <inputExclude>src/test/resources/json/primitive-type-array.json</inputExclude>
                        <inputExclude>src/test/resources/json/single-bank-account.json</inputExclude>
                        <inputExclude>src/test/resources/json/single-bank-account-wrong-field-type.json</inputExclude>
                        <inputExclude>src/test/resources/json/single-element-nested-array.json</inputExclude>
                        <inputExclude>src/test/resources/json/single-element-deep-nested.json</inputExclude>
                        <inputExclude>src/test/resources/json/single-element-nested.json</inputExclude>
                        <inputExclude>src/test/resources/json/single-element-nested-array-middle.json</inputExclude>
                        <inputExclude>src/test/resources/json/nested-array-then-start-object.json</inputExclude>
                        <inputExclude>src/test/resources/json/output/dataTypes.json</inputExclude>
                        <inputExclude>src/test/resources/json/elements-for-record-choice.json</inputExclude>
                        <inputExclude>src/test/resources/json/record-choice.avsc</inputExclude>
                        <inputExclude>src/test/resources/json/prov-events.json</inputExclude>
                        <inputExclude>src/test/resources/json/docs-example.json</inputExclude>
                        <inputExclude>src/test/resources/json/choice-of-string-or-array-record.json</inputExclude>
                        <inputExclude>src/test/resources/json/choice-of-string-or-array-record.avsc</inputExclude>
                        <inputExclude>src/test/resources/json/nested-choice-of-empty-array-or-string.json</inputExclude>
                        <inputExclude>src/test/resources/json/nested-choice-of-record-array-or-string.json</inputExclude>

                        <inputExclude>src/test/resources/syslog/syslog5424/log.txt</inputExclude>
                        <inputExclude>src/test/resources/syslog/syslog5424/log_all.txt</inputExclude>
                        <inputExclude>src/test/resources/syslog/syslog5424/log_mix.txt</inputExclude>
                        <inputExclude>src/test/resources/syslog/syslog5424/log_mix_in_error.txt</inputExclude>

                        <inputExclude>src/test/resources/text/testschema</inputExclude>

                        <inputExclude>src/test/resources/xml/dataWithArrayOfDifferentTypes.xml</inputExclude>
                        <inputExclude>src/test/resources/xml/field_with_sub-element.xml</inputExclude>
                        <inputExclude>src/test/resources/xml/people.xml</inputExclude>
                        <inputExclude>src/test/resources/xml/people2.xml</inputExclude>
                        <inputExclude>src/test/resources/xml/people3.xml</inputExclude>
                        <inputExclude>src/test/resources/xml/people_array.xml</inputExclude>
                        <inputExclude>src/test/resources/xml/people_array_simple.xml</inputExclude>
                        <inputExclude>src/test/resources/xml/people_cdata.xml</inputExclude>
                        <inputExclude>src/test/resources/xml/people_complex1.xml</inputExclude>
                        <inputExclude>src/test/resources/xml/people_complex2.xml</inputExclude>
                        <inputExclude>src/test/resources/xml/people_empty.xml</inputExclude>
                        <inputExclude>src/test/resources/xml/people_invalid.xml</inputExclude>
                        <inputExclude>src/test/resources/xml/people_map.xml</inputExclude>
                        <inputExclude>src/test/resources/xml/people_map2.xml</inputExclude>
                        <inputExclude>src/test/resources/xml/people_namespace.xml</inputExclude>
                        <inputExclude>src/test/resources/xml/people_nested.xml</inputExclude>
                        <inputExclude>src/test/resources/xml/people_no_attributes.xml</inputExclude>
                        <inputExclude>src/test/resources/xml/people_tag_in_characters.xml</inputExclude>
                        <inputExclude>src/test/resources/xml/people_with_header_and_comments.xml</inputExclude>
                        <inputExclude>src/test/resources/xml/person.xml</inputExclude>
                        <inputExclude>src/test/resources/xml/person_record.xml</inputExclude>
                        <inputExclude>src/test/resources/xml/testschema</inputExclude>
                        <inputExclude>src/test/resources/xml/testschema2</inputExclude>
                        <inputExclude>src/test/resources/xml/testschema3</inputExclude>
                        <inputExclude>src/test/resources/yaml/*.yaml</inputExclude>
                    </inputExcludes>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
