/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.nifi.processors.elasticsearch;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import org.apache.nifi.annotation.behavior.InputRequirement;
import org.apache.nifi.annotation.documentation.CapabilityDescription;
import org.apache.nifi.annotation.documentation.Tags;
import org.apache.nifi.annotation.lifecycle.OnScheduled;
import org.apache.nifi.components.PropertyDescriptor;
import org.apache.nifi.components.Validator;
import org.apache.nifi.elasticsearch.ElasticSearchClientService;
import org.apache.nifi.elasticsearch.ElasticsearchError;
import org.apache.nifi.elasticsearch.IndexOperationRequest;
import org.apache.nifi.elasticsearch.IndexOperationResponse;
import org.apache.nifi.expression.ExpressionLanguageScope;
import org.apache.nifi.flowfile.FlowFile;
import org.apache.nifi.processor.AbstractProcessor;
import org.apache.nifi.processor.ProcessContext;
import org.apache.nifi.processor.ProcessSession;
import org.apache.nifi.processor.Relationship;
import org.apache.nifi.processor.exception.ProcessException;
import org.apache.nifi.record.path.FieldValue;
import org.apache.nifi.record.path.RecordPath;
import org.apache.nifi.record.path.RecordPathResult;
import org.apache.nifi.record.path.util.RecordPathCache;
import org.apache.nifi.record.path.validation.RecordPathValidator;
import org.apache.nifi.serialization.RecordReader;
import org.apache.nifi.serialization.RecordReaderFactory;
import org.apache.nifi.serialization.RecordSetWriter;
import org.apache.nifi.serialization.RecordSetWriterFactory;
import org.apache.nifi.serialization.record.Record;
import org.apache.nifi.serialization.record.RecordFieldType;
import org.apache.nifi.serialization.record.RecordSchema;
import org.apache.nifi.serialization.record.util.DataTypeUtils;
import org.apache.nifi.util.StringUtils;

import java.io.InputStream;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

@InputRequirement(InputRequirement.Requirement.INPUT_REQUIRED)
@Tags({"json", "elasticsearch", "elasticsearch5", "elasticsearch6", "put", "index", "record"})
@CapabilityDescription("A record-aware Elasticsearch put processor that uses the official Elastic REST client libraries.")
public class PutElasticsearchRecord extends AbstractProcessor implements ElasticsearchRestProcessor {
    static final PropertyDescriptor RECORD_READER = new PropertyDescriptor.Builder()
        .name("put-es-record-reader")
        .displayName("Record Reader")
        .description("The record reader to use for reading incoming records from flowfiles.")
        .identifiesControllerService(RecordReaderFactory.class)
        .required(true)
        .build();

    static final PropertyDescriptor OPERATION_RECORD_PATH = new PropertyDescriptor.Builder()
        .name("put-es-record-operation-path")
        .displayName("Operation Record Path")
        .description("A record path expression to retrieve index operation setting from each record. If left blank, " +
                "all operations will be assumed to be index operations.")
        .addValidator(new RecordPathValidator())
        .required(false)
        .expressionLanguageSupported(ExpressionLanguageScope.FLOWFILE_ATTRIBUTES)
        .build();

    static final PropertyDescriptor ID_RECORD_PATH = new PropertyDescriptor.Builder()
        .name("put-es-record-id-path")
        .displayName("ID Record Path")
        .description("A record path expression to retrieve the ID field for use with Elasticsearch. If left blank " +
                "the ID will be automatically generated by Elasticsearch.")
        .addValidator(new RecordPathValidator())
        .expressionLanguageSupported(ExpressionLanguageScope.FLOWFILE_ATTRIBUTES)
        .build();

    static final PropertyDescriptor INDEX_RECORD_PATH = new PropertyDescriptor.Builder()
        .name("put-es-record-index-record-path")
        .displayName("Index Record Path")
        .description("A record path expression to retrieve the index field for use with Elasticsearch. If left blank " +
                "the index will be determined using the main index property.")
        .addValidator(new RecordPathValidator())
        .required(false)
        .expressionLanguageSupported(ExpressionLanguageScope.FLOWFILE_ATTRIBUTES)
        .build();

    static final PropertyDescriptor TYPE_RECORD_PATH = new PropertyDescriptor.Builder()
        .name("put-es-record-type-record-path")
        .displayName("Type Record Path")
        .description("A record path expression to retrieve the type field for use with Elasticsearch. If left blank " +
                "the type will be determined using the main type property.")
        .addValidator(new RecordPathValidator())
        .required(false)
        .expressionLanguageSupported(ExpressionLanguageScope.FLOWFILE_ATTRIBUTES)
        .build();

    static final PropertyDescriptor ERROR_RECORD_WRITER = new PropertyDescriptor.Builder()
        .name("put-es-record-error-writer")
        .displayName("Error Record Writer")
        .displayName("If this configuration property is set, the response from Elasticsearch will be examined for failed records " +
                "and the failed records will be written to a record set with this record writer service and sent to the \"errors\" " +
                "relationship.")
        .identifiesControllerService(RecordSetWriterFactory.class)
        .addValidator(Validator.VALID)
        .required(false)
        .build();

    static final List<PropertyDescriptor> DESCRIPTORS;
    static final Set<Relationship> RELATIONSHIPS;

    static {
        Set<Relationship> _rels = new HashSet<>();
        _rels.add(REL_SUCCESS);
        _rels.add(REL_FAILURE);
        _rels.add(REL_RETRY);
        _rels.add(REL_FAILED_RECORDS);

        RELATIONSHIPS = Collections.unmodifiableSet(_rels);

        List<PropertyDescriptor> _temp = new ArrayList<>();
        _temp.add(INDEX);
        _temp.add(TYPE);
        _temp.add(CLIENT_SERVICE);
        _temp.add(RECORD_READER);
        _temp.add(OPERATION_RECORD_PATH);
        _temp.add(ID_RECORD_PATH);
        _temp.add(INDEX_RECORD_PATH);
        _temp.add(TYPE_RECORD_PATH);
        _temp.add(LOG_ERROR_RESPONSES);
        _temp.add(ERROR_RECORD_WRITER);

        DESCRIPTORS = Collections.unmodifiableList(_temp);
    }

    @Override
    public Set<Relationship> getRelationships() {
        return RELATIONSHIPS;
    }

    @Override
    public final List<PropertyDescriptor> getSupportedPropertyDescriptors() {
        return DESCRIPTORS;
    }

    private RecordReaderFactory readerFactory;
    private RecordPathCache recordPathCache;
    private ElasticSearchClientService clientService;
    private RecordSetWriterFactory writerFactory;
    private boolean logErrors;

    @OnScheduled
    public void onScheduled(ProcessContext context) {
        this.readerFactory = context.getProperty(RECORD_READER).asControllerService(RecordReaderFactory.class);
        this.clientService = context.getProperty(CLIENT_SERVICE).asControllerService(ElasticSearchClientService.class);
        this.recordPathCache = new RecordPathCache(16);
        this.writerFactory = context.getProperty(ERROR_RECORD_WRITER).asControllerService(RecordSetWriterFactory.class);
        this.logErrors = context.getProperty(LOG_ERROR_RESPONSES).asBoolean();
    }


    @Override
    public void onTrigger(ProcessContext context, ProcessSession session) throws ProcessException {
        FlowFile input = session.get();
        if (input == null) {
            return;
        }

        try {
            BulkOperation bundle = buildOperations(input, context, session);
            IndexOperationResponse response = clientService.bulk(bundle.getOperationList());
            if (response.hasErrors()) {
                if(logErrors || getLogger().isDebugEnabled()) {
                    List<Map<String, Object>> errors = response.getItems();
                    ObjectMapper mapper = new ObjectMapper();
                    mapper.enable(SerializationFeature.INDENT_OUTPUT);
                    String output = String.format("An error was encountered while processing bulk operations. Server response below:\n\n%s", mapper.writeValueAsString(errors));

                    if (logErrors) {
                        getLogger().error(output);
                    } else {
                        getLogger().debug(output);
                    }
                }

                if (writerFactory != null) {
                    FlowFile errorFF = session.create(input);
                    try (OutputStream os = session.write(errorFF);
                         RecordSetWriter writer = writerFactory.createWriter(getLogger(), bundle.getSchema(), os )) {

                        int added = 0;
                        writer.beginRecordSet();
                        for (int index = 0; index < response.getItems().size(); index++) {
                            Map<String, Object> current = response.getItems().get(index);
                            String key = current.keySet().stream().findFirst().get();
                            Map<String, Object> inner = (Map<String, Object>) current.get(key);
                            if (inner.containsKey("error")) {
                                writer.write(bundle.getOriginalRecords().get(index));
                                added++;
                            }
                        }
                        writer.finishRecordSet();
                        writer.close();
                        os.close();

                        errorFF = session.putAttribute(errorFF, ATTR_RECORD_COUNT, String.valueOf(added));

                        session.transfer(errorFF, REL_FAILED_RECORDS);
                    } catch (Exception ex) {
                        getLogger().error("", ex);
                        session.remove(errorFF);
                        throw ex;
                    }
                }
            }

            session.transfer(input, REL_SUCCESS);
        } catch (ElasticsearchError ese) {
            String msg = String.format("Encountered a server-side problem with Elasticsearch. %s",
                    ese.isElastic() ? "Moving to retry." : "Moving to failure");
            getLogger().error(msg, ese);
            Relationship rel = ese.isElastic() ? REL_RETRY : REL_FAILURE;
            session.transfer(input, rel);
        } catch (Exception ex) {
            getLogger().error("Could not index documents.", ex);
            session.transfer(input, REL_FAILURE);
        }
    }

    private BulkOperation buildOperations(FlowFile flowFile, ProcessContext context, ProcessSession session) {
        try (final InputStream inStream = session.read(flowFile);
            final RecordReader reader = readerFactory.createRecordReader(flowFile, inStream, getLogger())) {
            List<IndexOperationRequest> operationList = new ArrayList<>();
            List<Record> originals = new ArrayList<>();

            final String index = context.getProperty(INDEX).evaluateAttributeExpressions(flowFile).getValue();
            final String type  = context.getProperty(TYPE).evaluateAttributeExpressions(flowFile).getValue();
            final String idPath = context.getProperty(ID_RECORD_PATH).isSet()
                ? context.getProperty(ID_RECORD_PATH).evaluateAttributeExpressions(flowFile).getValue()
                : null;
            final String indexPath = context.getProperty(INDEX_RECORD_PATH).isSet()
                ? context.getProperty(INDEX_RECORD_PATH).evaluateAttributeExpressions(flowFile).getValue()
                : null;
            final String typePath = context.getProperty(TYPE_RECORD_PATH).isSet()
                ? context.getProperty(TYPE_RECORD_PATH).evaluateAttributeExpressions(flowFile).getValue()
                : null;
            final String operationPath = context.getProperty(OPERATION_RECORD_PATH).isSet()
                ? context.getProperty(OPERATION_RECORD_PATH).evaluateAttributeExpressions(flowFile).getValue()
                : null;

            RecordPath path = idPath != null ? recordPathCache.getCompiled(idPath) : null;
            RecordPath iPath = indexPath != null ? recordPathCache.getCompiled(indexPath) : null;
            RecordPath tPath = typePath != null ? recordPathCache.getCompiled(typePath) : null;
            RecordPath oPath = operationPath != null ? recordPathCache.getCompiled(operationPath) : null;
            Record record;
            while ((record = reader.nextRecord()) != null) {
                final String idx = getFromRecordPath(record, iPath, index);
                final String t   = getFromRecordPath(record, tPath, type);
                final IndexOperationRequest.Operation o = getOperation(record, oPath);
                final String id  = path != null ? getFromRecordPath(record, path, null) : null;

                Map<String, Object> contentMap = (Map<String, Object>) DataTypeUtils.convertRecordFieldtoObject(record, RecordFieldType.RECORD.getRecordDataType(record.getSchema()));

                removeEmpty(contentMap);

                operationList.add(new IndexOperationRequest(idx, t, id, contentMap, o));
                originals.add(record);
            }

            return new BulkOperation(operationList, originals, reader.getSchema());
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    private void removeEmpty(Map<String, Object> input) {
        Map<String, Object> copy = new HashMap<>(input);

        for (Map.Entry<String, Object> entry : input.entrySet()) {
            if (entry.getValue() == null) {
               copy.remove(entry.getKey());
            } else {
                if (StringUtils.isBlank(entry.getValue().toString())) {
                    copy.remove(entry.getKey());
                } else if (entry.getValue() instanceof Map) {
                    removeEmpty((Map<String, Object>) entry.getValue());
                } else if (entry.getValue() instanceof List) {
                    for (Object value : (List)entry.getValue()) {
                        if (value instanceof Map) {
                            removeEmpty((Map<String, Object>) value);
                        }
                    }
                }
            }
        }

        input.clear();
        input.putAll(copy);
    }

    private String getId(Record record, RecordPath path) {
        RecordPathResult result = path.evaluate(record);
        Optional<FieldValue> value = result.getSelectedFields().findFirst();
        if (value.isPresent() && value.get().getValue() != null) {
            return value.get().getValue().toString();
        } else {
            throw new RuntimeException("Missing ID field in one of the records.");
        }
    }

    private IndexOperationRequest.Operation getOperation(Record record, RecordPath path) {
        String val = getFromRecordPath(record, path, IndexOperationRequest.Operation.Index.name()).toLowerCase();
        IndexOperationRequest.Operation retVal;

        switch (val) {
            case "create":
                retVal = IndexOperationRequest.Operation.Create;
                break;
            case "delete":
                retVal = IndexOperationRequest.Operation.Delete;
                break;
            case "index":
                retVal = IndexOperationRequest.Operation.Index;
                break;
            case "update":
                retVal = IndexOperationRequest.Operation.Update;
                break;
            case "upsert":
                retVal = IndexOperationRequest.Operation.Upsert;
                break;
            default:
                throw new ProcessException(String.format("Invalid Elasticsearch operation %s", val));
        }

        return retVal;
    }

    private String getFromRecordPath(Record record, RecordPath path, final String fallback) {
        if (path == null) {
            return fallback;
        }

        RecordPathResult result = path.evaluate(record);
        Optional<FieldValue> value = result.getSelectedFields().findFirst();
        if (value.isPresent() && value.get().getValue() != null) {
            FieldValue fieldValue = value.get();
            if (!fieldValue.getField().getDataType().getFieldType().equals(RecordFieldType.STRING) ) {
                throw new ProcessException(
                    String.format("Field referenced by %s must be a string.", path.getPath())
                );
            }

            fieldValue.updateValue(null);

            String retVal = fieldValue.getValue().toString();

            return retVal;
        } else {
            return fallback;
        }
    }

    class BulkOperation {
        private List<IndexOperationRequest> operationList;
        private List<Record> originalRecords;
        private RecordSchema schema;

        BulkOperation(List<IndexOperationRequest> operationList, List<Record> originalRecords, RecordSchema schema) {
            this.operationList = operationList;
            this.originalRecords = originalRecords;
            this.schema = schema;
        }

        public List<IndexOperationRequest> getOperationList() {
            return operationList;
        }

        public List<Record> getOriginalRecords() {
            return originalRecords;
        }

        public RecordSchema getSchema() {
            return schema;
        }
    }
}
