# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#create mapping
PUT:messages/:{ "mappings":{"message":{ "properties":{ "msg":{"type":"keyword"}}}}}
#add document
PUT:messages/message/1:{ "msg":"one" }
PUT:messages/message/2:{ "msg":"two" }
PUT:messages/message/3:{ "msg":"two" }
PUT:messages/message/4:{ "msg":"three" }
PUT:messages/message/5:{ "msg":"three" }
PUT:messages/message/6:{ "msg":"three" }
PUT:messages/message/7:{ "msg":"four" }
PUT:messages/message/8:{ "msg":"four" }
PUT:messages/message/9:{ "msg":"four" }
PUT:messages/message/10:{ "msg":"four" }
PUT:messages/message/11:{ "msg":"five" }
PUT:messages/message/12:{ "msg":"five" }
PUT:messages/message/13:{ "msg":"five" }
PUT:messages/message/14:{ "msg":"five" }
PUT:messages/message/15:{ "msg":"five" }