/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_nifi_nar_sharedlib_TestJNI */

#ifndef _Included_org_apache_nifi_nar_sharedlib_TestJNI
#define _Included_org_apache_nifi_nar_sharedlib_TestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_nifi_nar_sharedlib_TestJNI
 * Method:    testJniMethod
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_apache_nifi_nar_sharedlib_TestJNI_testJniMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
